services:
  stats-server:
    build: ewm-stats/stat-server/
    ports:
      - "9090:9090"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_NAME=statServiceDb
      - DB_HOST=stats-db
      - DB_PORT=5432
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    ports:
      - "5437:5432"
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=statServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-db:
    image: postgres:16.1
    ports:
      - "5438:5432"
    container_name: ewm-db-container
    environment:
      - POSTGRES_DB=exploreMainServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ewm-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - STAT_SERVER_URL=http://stats-server:9090
      - DB_NAME=exploreMainServiceDb
      - DB_HOST=ewm-db
      - DB_PORT=5432