version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_NAME=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - TZ=Europe/Moscow
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - DB_HOST=stats-db
      - DB_NAME=stats-db
      - DB_PORT=5432
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - TZ=Europe/Moscow
    volumes:
        - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
  ewm-server:
    build: main-service
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_HOST=ewm-db
      - DB_NAME=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - TZ=Europe/Moscow
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "5433:5433"
    environment:
      - DB_HOST=ewm-db
      - DB_NAME=ewm-db
      - DB_PORT=5433
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - TZ=Europe/Moscow
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro